// Generated by CoffeeScript 1.11.1
var HomeModule;

HomeModule = {
  component: require('./home')({
    store: require('./store'),
    actions: require('./actions')
  })
};

module.exports = HomeModule;
